// Generated by CoffeeScript 1.3.3
(function() {
  var Settings, root;

  Settings = {
    defaults: {
      scrollStepSize: 60,
      linkHintCharacters: "sadfjklewcmpgh",
      filterLinkHints: false,
      hideHud: false,
      userDefinedLinkHintCss: "div > .vimiumHintMarker {\n/* linkhint boxes */\nbackground-color: yellow;\nborder: 1px solid #E3BE23;\n}\n\ndiv > .vimiumHintMarker span {\n/* linkhint text */\ncolor: black;\nfont-weight: bold;\nfont-size: 12px;\n}\n\ndiv > .vimiumHintMarker > .matchingCharacter {\n}",
      excludedUrls: "http*://mail.google.com/*\nhttp*://www.google.com/reader/*",
      previousPatterns: "prev,previous,back,<,\u2190,\xab,\u226a,<<",
      nextPatterns: "next,more,>,\u2192,\xbb,\u226b,>>"
    },
    init: function() {
      var key;
      if (!this.has("settingsVersion")) {
        for (key in localStorage) {
          if (key === "filterLinkHints") {
            localStorage[key] = localStorage[key] === "true" ? true : false;
          } else {
            localStorage[key] = JSON.stringify(localStorage[key]);
          }
        }
        return this.set("settingsVersion", Utils.getCurrentVersion());
      }
    },
    get: function(key) {
      if (key in localStorage) {
        return JSON.parse(localStorage[key]);
      } else {
        return this.defaults[key];
      }
    },
    set: function(key, value) {
      if (value === this.defaults[key]) {
        return this.clear(key);
      } else {
        return localStorage[key] = JSON.stringify(value);
      }
    },
    clear: function(key) {
      return delete localStorage[key];
    },
    has: function(key) {
      return key in localStorage;
    }
  };

  Settings.init();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Settings = Settings;

}).call(this);
